# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
array = np.ones(10) * 5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
np.random.rand(1)

array([0.71249846])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
np.random.randn(5,5)

array([[-0.90310834,  0.48732749, -0.36033579,  0.1349833 ,  0.59984811],
       [ 0.62357219,  0.62989136,  0.23901131,  0.52424357, -1.32361747],
       [ 0.0476721 , -1.65634902, -0.81221247, -0.09702304, -0.90054435],
       [-1.53124589,  1.18509441,  1.09028414,  0.88964303, -1.04420379],
       [-0.30627369, -0.71213327, -1.38364971,  0.22359624,  2.90926521]])

#### Create the following matrix:

In [19]:
arr = np.arange(0.01,1.01)
arr

array([0.01])

In [20]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Create a 5x5 matrix with 1s on the border and 0s inside (without using loops).

In [21]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Generate a 1D array with 20 evenly spaced points between 0 and 100. Then reshape it into a 4x5 matrix and calculate the sum of each row.

In [29]:

x = np.linspace(0, 100, 20)
x = x.reshape(4, 5)
row_sums = np.sum(x, axis=1)
print(row_sums)

[ 52.63157895 184.21052632 315.78947368 447.36842105]


#### Create a 4x4 array of random numbers between 0-10. Then subtract the mean of each row from the corresponding row using broadcasting.

In [30]:
arr = np.random.uniform(0, 10, (4, 4))
row_means = np.mean(arr, axis=1)
result = arr - row_means[:, np.newaxis]
result

array([[ 0.85022629, -4.96739978,  4.75042722, -0.63325372],
       [ 1.76819487, -1.35468528, -0.70062453,  0.28711494],
       [-3.04380718,  4.97723734, -2.02662389,  0.09319372],
       [-1.18073877,  1.24977007,  3.19254924, -3.26158053]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [34]:
mat[3][4]

np.int64(20)

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
mat[0:3][0:1]

array([[1, 2, 3, 4, 5]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [48]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [49]:
total = np.sum(mat)
total

np.int64(325)

#### Get the standard deviation of the values in mat

In [50]:
std_Dev = np.std(mat)
std_Dev

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [51]:
column_sums = np.sum(mat, axis=0)
column_sums

array([55, 60, 65, 70, 75])

# Great Job!